version: '3'
services:
  httpd:
    image: local/httpd
    build: docker/httpd
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/:/var/www/:cached

  composer:
    image: composer:1.8
    container_name: 'composer'
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www/:cached
      - vendor:/var/www/vendor/
    depends_on:
      - httpd

  mysql:
    image: local/mysql
    build: docker/mysql
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: example
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "8025:8025"

volumes:
  vendor:
  mysql-data:
    driver: local
